### ISSUE TITLE
Bug Blocking Facebook when adding Locations

### ISSUE THREAD

**Issue by brandonreid** [usebenchmark/benchmarkplaces#34]

**Comment by brandonreid** [comment]
![screen shot 2015-04-07 at 3 35 47 pm](https://cloud.githubusercontent.com/assets/6776415/7034090/5aa452ae-dd3c-11e4-8f84-1d17cc5e6ea1.png)

^ the server error

**Comment by brandonreid** [comment]
@ken - do you think you can prioritize this one so I can add the updated facebook chart?

**Comment by kennethkoontz** [comment]
Did you run `pip install -r requirements.txt`?
