### ISSUE TITLE
Yelp Phone Search Method

### ISSUE THREAD

**Issue by jordanskole** [usebenchmark/benchmarkplaces#8]

**Comment by kennethkoontz** [comment]
@jordanskole, what do we need to do here to resolve this?

**Comment by jordanskole** [comment]
You can close this one, at some point I would like the ability to edit a location and ad the place using the placeid, which is specifically relevant to yelp because it's easy to find `my-chain-restaurant-dansville` but that doesn't apply to this issue.

**Comment by kennethkoontz** [comment]
Yeah, it's a good idea. Sometimes yelp doesn't find a location with search for whatever reason, but if we manually specify an ID we could easily get around it.
